name: C/C++ CI

on:
  push:
    branches: [ "patch-1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: g++ -std=c++17 -L/usr/lib/x86_64-linux-gnu main.cpp -o program.out
    - name: execute
      run: ./program.out
